from __future__ import annotations

from pathlib import Path

from ibwd.scanner.filesystem import classify_file, hash_file, scan_files


def test_classify_file():
    assert classify_file("src/app.py") == "source"
    assert classify_file("tests/test_app.py") == "test"
    assert classify_file("src/app.test.ts") == "test"
    assert classify_file("README.md") == "doc"
    assert classify_file("pyproject.toml") == "config"
    assert classify_file("Dockerfile") == "config"
    assert classify_file("data.bin") == "other"


def test_scan_files_respects_gitignore(git_repo: Path):
    scanned = scan_files(git_repo)
    paths = {f.path for f in scanned}

    assert "ignored.txt" not in paths
    assert ".git/config" not in paths
    assert "src/app.py" in paths
    assert "tests/test_app.py" in paths


def test_scan_files_classifies_correctly(git_repo: Path):
    scanned = {f.path: f.kind for f in scan_files(git_repo)}

    assert scanned["src/app.py"] == "source"
    assert scanned["tests/test_app.py"] == "test"
    assert scanned["README.md"] == "doc"
    assert scanned["pyproject.toml"] == "config"


def test_hash_is_stable_and_content_sensitive(git_repo: Path):
    path = git_repo / "src" / "app.py"
    h1 = hash_file(path)
    h2 = hash_file(path)
    assert h1 == h2

    path.write_text("def main():\n    return 2\n")
    h3 = hash_file(path)
    assert h3 != h1


def test_vendor_and_generated_files_are_classified_and_not_indexed(tmp_path):
    from ibwd.graph.database import connect
    from ibwd.scan import run_scan

    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "app.py").write_text("def real():\n    return 1\n")
    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "lib.py").write_text("def vendored():\n    return 1\n")
    (tmp_path / "static").mkdir()
    (tmp_path / "static" / "bundle.min.js").write_text("function a(){return 1}\n")
    (tmp_path / "static" / "big.js").write_text("function b(){return 1}" + ";var x=1" * 400 + "\n")  # one huge line
    (tmp_path / "src" / "gen.py").write_text("# @generated by protoc. DO NOT EDIT\ndef generated_fn():\n    return 1\n")
    (tmp_path / "src" / "legit.js").write_text("// ordinary code\nfunction ok() {\n  return 1;\n}\n" * 100)

    assert classify_file("vendor/lib.py") == "vendor"
    assert classify_file("static/bundle.min.js") == "generated"
    assert classify_file("src/legit.js") == "source"

    run_scan(tmp_path)
    conn = connect(tmp_path / ".ibwd" / "graph.db")
    kinds = {r["file_path"]: r["kind"] for r in conn.execute("SELECT file_path, kind FROM nodes WHERE node_type = 'File'")}
    symbols = {r["name"] for r in conn.execute("SELECT name FROM nodes WHERE node_type IN ('Function', 'Class', 'Method')")}

    assert kinds["vendor/lib.py"] == "vendor"
    assert kinds["static/bundle.min.js"] == "generated"
    assert kinds["static/big.js"] == "generated"  # minified-looking content
    assert kinds["src/gen.py"] == "generated"  # generator banner
    assert kinds["src/legit.js"] == "source"
    assert symbols == {"real", "ok"}  # nothing from vendored/generated files


def test_reclassified_file_loses_stale_symbols(tmp_path):
    from ibwd.graph.database import connect
    from ibwd.scan import run_scan

    (tmp_path / "lib.py").write_text("def f():\n    return 1\n")
    run_scan(tmp_path)
    conn = connect(tmp_path / ".ibwd" / "graph.db")
    assert conn.execute("SELECT COUNT(*) FROM nodes WHERE name = 'f'").fetchone()[0] == 1
    conn.close()

    (tmp_path / "lib.py").write_text("# @generated\ndef f():\n    return 1\n")
    run_scan(tmp_path)
    conn = connect(tmp_path / ".ibwd" / "graph.db")
    assert conn.execute("SELECT COUNT(*) FROM nodes WHERE name = 'f'").fetchone()[0] == 0
