"""Filesystem scanner: walk a repo respecting .gitignore, classify files, hash contents."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import pathspec
import xxhash

ALWAYS_IGNORE = {".git", ".ibwd", "__pycache__", ".venv", "node_modules", ".pytest_cache", ".mypy_cache"}

TEST_NAME_PATTERNS = ("test_", "_test.", ".test.", ".spec.")
TEST_DIR_NAMES = {"test", "tests", "__tests__", "spec"}

DOC_EXTENSIONS = {".md", ".rst", ".txt", ".adoc"}
DOC_NAMES = {"readme", "changelog", "license", "contributing", "authors", "notice"}
DOC_DIR_NAMES = {"docs", "doc"}

CONFIG_EXTENSIONS = {".toml", ".yaml", ".yml", ".json", ".ini", ".cfg", ".env"}
CONFIG_NAMES = {
    "dockerfile", "makefile", ".gitignore", ".dockerignore", ".editorconfig",
    "pyproject.toml", "package.json", "package-lock.json", "poetry.lock",
    "requirements.txt", "setup.py", "setup.cfg", "uv.lock",
}

# Third-party copies and machine-generated code: kept visible as files, but never indexed
# for symbols/edges (they pollute results — e.g. a minified library adds thousands of "functions").
VENDOR_DIR_NAMES = {"vendor", "vendors", "third_party", "third-party", "thirdparty", "bower_components", "site-packages"}
GENERATED_NAME_PATTERNS = (".min.", "-min.", ".bundle.", ".generated.", "_pb2.py", "_pb2_grpc.py", ".pb.go", ".g.dart")
# A generator banner names the generator ("Generated by protoc", "auto-generated by ...", "Code generated by ... DO NOT EDIT") or says
# `@generated` / `DO NOT EDIT`. The bare word "autogenerated" is not evidence: hand-written files say "imagine this file is autogenerated".
GENERATED_BANNER = re.compile(rb"@generated|do not edit|code generated by|(?:auto-?generated|automatically generated|generated) (?:by|using|with)\b")
MINIFIED_MIN_BYTES = 1500
MINIFIED_AVG_LINE_LENGTH = 200

SOURCE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".go", ".rs", ".java", ".c", ".h",
    ".cpp", ".hpp", ".rb", ".php", ".cs", ".swift", ".kt", ".scala", ".sh",
}


@dataclass # dataclass is used for convenience, but we don't need to compare or sort these objects
class ScannedFile:
    """
    Represents a file scanned from the filesystem.
    E.g., a file in a git repository, 
    with its path relative to the repo root, 
    its classification (source, test, doc, config, or other), 
    and a hash of its contents.
    """
    path: str  # posix-style, relative to repo root e.g posix-style: "src/ibwd/scanner/filesystem.py"; windows-style: "src\ibwd\scanner\filesystem.py"  
    kind: str  # source | test | doc | config | vendor | generated | other; source = code, test = test code, doc = documentation, config = configuration file, other = anything else
    content_hash: str # 64-bit hash of file contents, hex-encoded


def _load_gitignore_spec(repo_root: Path) -> pathspec.PathSpec:
    """
    Load the .gitignore file from the repo root and return a PathSpec object for matching files.
    E.g., if the .gitignore file contains "*.pyc" in first line and second line is "build/", 
    then the PathSpec object will match any file with a .pyc extension 
    and any file in the build/ directory.
    """
    gitignore = repo_root / ".gitignore" # .gitignore file is expected to be in the root of the repository
    lines: list[str] = [] # Initialize an empty list to hold the lines from the .gitignore file
    if gitignore.exists(): # If the .gitignore file exists, read its contents and split it into lines
        lines = gitignore.read_text(errors="ignore").splitlines() # Read the .gitignore file, ignoring any errors, and split it into lines
    return pathspec.PathSpec.from_lines("gitignore", lines) # Create a PathSpec object from the lines of the .gitignore file, using the "gitignore" syntax


def classify_file(rel_path: str) -> str:
    """Classify a file based on its path and name.
    Returns one of: "source", "test", "doc", "config", "other"
    """
    p = Path(rel_path) # Create a Path object from the relative path of the file
    name_lower = p.name.lower() # Get the name of the file in lowercase
    ext = p.suffix.lower() # Get the file extension in lowercase
    parts_lower = {part.lower() for part in p.parts[:-1]} # Get the parts of the path (excluding the file name) in lowercase e.g., for "src/ibwd/scanner/filesystem.py", parts_lower will be {"src", "ibwd", "scanner"}

    if ext in SOURCE_EXTENSIONS:
        if parts_lower & VENDOR_DIR_NAMES:
            return "vendor"
        if any(pat in name_lower for pat in GENERATED_NAME_PATTERNS):
            return "generated"

    if parts_lower & TEST_DIR_NAMES or any(pat in name_lower for pat in TEST_NAME_PATTERNS): # If the file is in a test directory or its name matches a test pattern, classify it as a test file
        return "test"
    if ext in CONFIG_EXTENSIONS or name_lower in CONFIG_NAMES: # If the file has a configuration file extension or its name matches a known configuration file name, classify it as a config file
        return "config"
    if ext in DOC_EXTENSIONS or name_lower.split(".")[0] in DOC_NAMES or parts_lower & DOC_DIR_NAMES: # If the file has a documentation file extension, its name matches a known documentation file name, or it is in a documentation directory, classify it as a doc file
        return "doc"
    if ext in SOURCE_EXTENSIONS: # If the file has a source code file extension, classify it as a source file
        return "source"
    return "other"


def looks_generated(data: bytes) -> bool:
    """Content heuristics for generated/minified code: a generator banner, or very long average lines."""
    head = data[:1024].lower()
    if GENERATED_BANNER.search(head):
        return True
    return len(data) >= MINIFIED_MIN_BYTES and len(data) / (data.count(b"\n") + 1) > MINIFIED_AVG_LINE_LENGTH


def hash_file(path: Path) -> str:
    """Return a 64-bit hash of the file contents, hex-encoded."""
    hasher = xxhash.xxh3_64() # Create a new xxhash object for hashing the file contents
    hasher.update(path.read_bytes()) # Read the contents of the file and update the hash object with it
    return hasher.hexdigest()


def scan_files(repo_root: Path) -> list[ScannedFile]:
    """Walk repo_root respecting .gitignore + ALWAYS_IGNORE, return classified+hashed files."""
    spec = _load_gitignore_spec(repo_root) # Load the .gitignore file from the repo root and create a PathSpec object for matching files
    results: list[ScannedFile] = [] # Initialize an empty list to hold the scanned files

    for path in sorted(repo_root.rglob("*")):# Recursively walk the repo_root directory and its subdirectories, yielding all files and directories
        if not path.is_file(): # If the path is not a file (e.g., it is a directory), skip it and continue to the next path
            continue
        rel_path = path.relative_to(repo_root) # Get the relative path of the file with respect to the repo_root directory
        if any(part in ALWAYS_IGNORE for part in rel_path.parts): # If any part of the relative path is in the ALWAYS_IGNORE set, skip it and continue to the next path
            continue
        rel_posix = rel_path.as_posix() # Convert the relative path to a POSIX-style string (e.g., "src/ibwd/scanner/filesystem.py")
        if spec.match_file(rel_posix): # If the relative path matches any pattern in the .gitignore file, skip it and continue to the next path
            continue
        try: # Read the file once: hash it, and inspect source files for generated/minified content
            data = path.read_bytes()
        except OSError:
            continue
        kind = classify_file(rel_posix)
        if kind == "source" and looks_generated(data):
            kind = "generated"
        results.append(ScannedFile(path=rel_posix, kind=kind, content_hash=xxhash.xxh3_64(data).hexdigest())) # Create a ScannedFile object with the relative path, classification, and content hash of the file, and append it to the results list

    return results
