"""Filesystem scanner: walk a repo respecting .gitignore, classify files, hash contents."""

from __future__ import annotations

import re
from collections import OrderedDict
import stat
from threading import RLock
from dataclasses import dataclass
from pathlib import Path

import pathspec
import xxhash

ALWAYS_IGNORE = {".git", ".ibwd", "__pycache__", ".venv", "node_modules", ".pytest_cache", ".mypy_cache"}

TEST_NAME_PATTERNS = ("test_", "_test.", ".test.", ".spec.")
TEST_DIR_NAMES = {"test", "tests", "__tests__", "spec"}

DOC_EXTENSIONS = {".md", ".rst", ".txt", ".adoc"}
DOC_NAMES = {"readme", "changelog", "license", "contributing", "authors", "notice"}
DOC_DIR_NAMES = {"docs", "doc"}

CONFIG_EXTENSIONS = {".toml", ".yaml", ".yml", ".json", ".ini", ".cfg", ".env"}
CONFIG_NAMES = {
    "dockerfile", "makefile", ".gitignore", ".dockerignore", ".editorconfig",
    "pyproject.toml", "package.json", "package-lock.json", "poetry.lock",
    "requirements.txt", "setup.py", "setup.cfg", "uv.lock",
}

# Third-party copies and machine-generated code: kept visible as files, but never indexed
# for symbols/edges (they pollute results — e.g. a minified library adds thousands of "functions").
VENDOR_DIR_NAMES = {"vendor", "vendors", "third_party", "third-party", "thirdparty", "bower_components", "site-packages"}
GENERATED_NAME_PATTERNS = (".min.", "-min.", ".bundle.", ".generated.", "_pb2.py", "_pb2_grpc.py", ".pb.go", ".g.dart")
# A generator banner says `@generated` / `DO NOT EDIT`, or "code generated by" (the Go convention), or "auto-generated by/using/with ...".
# ("automatically generated by utils/generate-snowball.py" data modules stay indexed: they are importable source in the benchmark scope.)
# Neither the bare word "autogenerated" ("imagine this file is autogenerated") nor plain "generated by" (prose in a docstring) is evidence.
GENERATED_BANNER = re.compile(rb"@generated|do not edit|code generated by|auto-?generated (?:by|using|with)\b")
MINIFIED_MIN_BYTES = 1500
MINIFIED_AVG_LINE_LENGTH = 200

SOURCE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".go", ".rs", ".java", ".c", ".h",
    ".cpp", ".hpp", ".rb", ".php", ".cs", ".swift", ".kt", ".scala", ".sh",
}


@dataclass # dataclass is used for convenience, but we don't need to compare or sort these objects
class ScannedFile:
    """
    Represents a file scanned from the filesystem.
    E.g., a file in a git repository, 
    with its path relative to the repo root, 
    its classification (source, test, doc, config, or other), 
    and a hash of its contents.
    """
    path: str  # posix-style, relative to repo root e.g posix-style: "src/ibwd/scanner/filesystem.py"; windows-style: "src\ibwd\scanner\filesystem.py"  
    kind: str  # source | test | doc | config | vendor | generated | other; source = code, test = test code, doc = documentation, config = configuration file, other = anything else
    content_hash: str # 64-bit hash of file contents, hex-encoded


def _load_gitignore_spec(repo_root: Path) -> pathspec.PathSpec:
    """
    Load the .gitignore file from the repo root and return a PathSpec object for matching files.
    E.g., if the .gitignore file contains "*.pyc" in first line and second line is "build/", 
    then the PathSpec object will match any file with a .pyc extension 
    and any file in the build/ directory.
    """
    gitignore = repo_root / ".gitignore" # .gitignore file is expected to be in the root of the repository
    lines: list[str] = [] # Initialize an empty list to hold the lines from the .gitignore file
    if gitignore.exists(): # If the .gitignore file exists, read its contents and split it into lines
        lines = gitignore.read_text(errors="ignore").splitlines() # Read the .gitignore file, ignoring any errors, and split it into lines
    return pathspec.PathSpec.from_lines("gitignore", lines) # Create a PathSpec object from the lines of the .gitignore file, using the "gitignore" syntax


def classify_file(rel_path: str) -> str:
    """Classify a file based on its path and name.
    Returns one of: "source", "test", "doc", "config", "other"
    """
    p = Path(rel_path) # Create a Path object from the relative path of the file
    name_lower = p.name.lower() # Get the name of the file in lowercase
    ext = p.suffix.lower() # Get the file extension in lowercase
    parts_lower = {part.lower() for part in p.parts[:-1]} # Get the parts of the path (excluding the file name) in lowercase e.g., for "src/ibwd/scanner/filesystem.py", parts_lower will be {"src", "ibwd", "scanner"}

    if ext in SOURCE_EXTENSIONS:
        if parts_lower & VENDOR_DIR_NAMES:
            return "vendor"
        if any(pat in name_lower for pat in GENERATED_NAME_PATTERNS):
            return "generated"

    if parts_lower & TEST_DIR_NAMES or any(pat in name_lower for pat in TEST_NAME_PATTERNS): # If the file is in a test directory or its name matches a test pattern, classify it as a test file
        return "test"
    if ext in CONFIG_EXTENSIONS or name_lower in CONFIG_NAMES: # If the file has a configuration file extension or its name matches a known configuration file name, classify it as a config file
        return "config"
    if ext in DOC_EXTENSIONS or name_lower.split(".")[0] in DOC_NAMES or parts_lower & DOC_DIR_NAMES: # If the file has a documentation file extension, its name matches a known documentation file name, or it is in a documentation directory, classify it as a doc file
        return "doc"
    if ext in SOURCE_EXTENSIONS: # If the file has a source code file extension, classify it as a source file
        return "source"
    return "other"


def looks_generated(data: bytes) -> bool:
    """Content heuristics for generated/minified code: a generator banner, or very long average lines."""
    head = data[:1024].lower()
    if GENERATED_BANNER.search(head):
        return True
    return len(data) >= MINIFIED_MIN_BYTES and len(data) / (data.count(b"\n") + 1) > MINIFIED_AVG_LINE_LENGTH


def hash_file(path: Path) -> str:
    """Return a 64-bit hash of the file contents, hex-encoded."""
    hasher = xxhash.xxh3_64() # Create a new xxhash object for hashing the file contents
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            hasher.update(block)
    return hasher.hexdigest()


_fingerprints = OrderedDict()
_fingerprint_lock = RLock()


def stat_identity(value):
    return (value.st_dev, value.st_ino, value.st_mode, value.st_size,
            value.st_mtime_ns, value.st_ctime_ns)


def file_fingerprint(path, use_cache=True):
    """Track metadata changes in process; stream bytes when content needs hashing."""
    before = path.stat(follow_symlinks=False)
    if not stat.S_ISREG(before.st_mode):
        raise ValueError('Inventory requires regular files')
    identity = stat_identity(before)
    key = str(path.absolute())
    with _fingerprint_lock:
        cached = _fingerprints.get(key)
        if use_cache and cached and cached[0] == identity and cached[2] is looks_generated:
            _fingerprints.move_to_end(key)
            return cached[1]
    hasher, size, newlines, head = xxhash.xxh3_64(), 0, 0, b''
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            hasher.update(block)
            size += len(block)
            newlines += block.count(b'\n')
            if len(head) < 1024:
                head += block[:1024 - len(head)]
    if stat_identity(path.stat(follow_symlinks=False)) != identity:
        raise ValueError('File changed while hashing; retry when edits settle')
    generated = looks_generated(head) or (
        size >= MINIFIED_MIN_BYTES and size / (newlines + 1) > MINIFIED_AVG_LINE_LENGTH)
    result = (hasher.hexdigest(), generated)
    with _fingerprint_lock:
        _fingerprints[key] = (identity, result, looks_generated)
        _fingerprints.move_to_end(key)
        while len(_fingerprints) > 16384:
            _fingerprints.popitem(last=False)
    return result


def scan_files(repo_root: Path, use_cache: bool = True) -> list[ScannedFile]:
    """Prune ignored trees, apply nested gitignores and hash the readable inventory."""
    import os
    results: list[ScannedFile] = []
    inherited = {}
    def walk_error(error):
        raise error
    for directory, directories, names in os.walk(repo_root, followlinks=False, onerror=walk_error):
        folder = Path(directory)
        specs = list(inherited.get(folder, []))
        ignore = folder / '.gitignore'
        if ignore.is_file():
            specs.append((folder, pathspec.PathSpec.from_lines('gitignore', ignore.read_text().splitlines())))
        def ignored(path, is_dir=False):
            matched = False
            for base, spec in specs:
                relative = path.relative_to(base).as_posix() + ('/' if is_dir else '')
                for pattern in spec.patterns:
                    if pattern.include is not None and pattern.match_file(relative) is not None:
                        matched = pattern.include
            return matched
        directories[:] = sorted(name for name in directories if name not in ALWAYS_IGNORE
                                and not (folder / name).is_symlink() and not ignored(folder / name, True))
        for name in directories:
            inherited[folder / name] = specs
        for name in sorted(names):
            path = folder / name
            if path.is_symlink() or ignored(path) or not path.is_file():
                continue
            digest, generated = file_fingerprint(path, use_cache)
            rel_posix = path.relative_to(repo_root).as_posix()
            kind = classify_file(rel_posix)
            if kind == 'source' and generated:
                kind = 'generated'
            results.append(ScannedFile(rel_posix, kind, digest))
    return sorted(results, key=lambda file: file.path)
